# -*- coding: utf-8 -*-
"""CS682_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4Zt_mdbJ5S3YVuPnE7zKn37SBuZaFoD
"""

import requests
from geopy.geocoders import Nominatim
import re

StrLocation = input("Enter Location:")
if re.search('[a-zA-Z]', StrLocation):
  geolocator = Nominatim(user_agent='myapplication')
  location = geolocator.geocode(StrLocation)
  latValue = location.latitude
  lonValue = location.longitude
else:
  latValue = StrLocation.split(',')[0]
  lonValue = StrLocation.split(',')[1]

r = requests.get('https://power.larc.nasa.gov/api/temporal/hourly/point?start=20220308&end=20220309&latitude='+str(latValue)+'&longitude='+str(lonValue)+'&community=ag&parameters=TS%2CALLSKY_SFC_UVA&format=json&header=true&time-standard=lst')

r.json()